#!/bin/bash

username=$0
hostname=$1

# Функция установки из aur
function aur {
cd /tmp
git clone https://aur.archlinux.org/$1.git
chown -R $username:users /tmp/$1
chown -R $username:users /tmp/$1/PKGBUILD
cd $1
sudo -u $username makepkg -si --noconfirm
cd ..
rm -rf $1
}

echo '--------------------------------------------------'
echo 'Install Arch Linux '$username'@'$hostname
echo '--------------------------------------------------'
pacman -Sy sed --noconfirm

echo '>> Russification...'
loadkeys ru
setfont cyr-sun16
echo -e 'KEYMAP=ru\nFONT=cyr-sun16\n' > /etc/vconsole.conf

sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
sed -i 's/#ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen

echo -e 'LANG=ru_RU.UTF-8' > /etc/locale.conf
export LANG=ru_RU.UTF-8

echo '>> Настройка времени'
timedatectl set-ntp true
hwclock --systohc --utc
timedatectl status

echo '>> Имя компьютера '$hostname
echo $hostname > /etc/hostname
echo -e '127.0.0.1 localhost\n::1 localhost\n' > /etc/hosts

# Настройка администратора и создание пользователя $username
echo '>> Пароль root'
passwd
useradd -G wheel -s /bin/bash -m $username
echo '>> Пароль пользователя '$username
passwd $username

echo '>> Собираем ядро'
mkinitcpio -p linux

echo '>> Настройка прав администратора'
echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers
sed -i 's/#Color/Color/g' /etc/pacman.conf

echo '>> Разблокировка и обновление x32 библиотек'
echo -e '[multilib]\nInclude = /etc/pacman.d/mirrorlist\n' >> /etc/pacman.conf

pacman -Syy

echo '>> Установка GRUB'
pacman -S grub efibootmgr --noconfirm #для mbr удалить efibootmgr
#pacman -S amd-ucode --noconfirm #раскомментировать строку для AMD процессора
#pacman -S intel-ucode --noconfirm #раскомментировать строку для AMD процессора
grub-install /dev/sda
echo '>> Настройка GRUB'
grub-mkconfig -o /boot/grub/grub.cfg
sed -i 's/set timeout=5/set timeout=0/g' /boot/grub/grub.cfg

echo '>> Установка xorg и mesa'
pacman -S xorg xorg-xinit mesa --noconfirm

echo '--------------------------------------------------'
echo '|              Установка драйверов               |'
echo '--------------------------------------------------'
#cd /etc/X11/xorg.conf.d/

#echo 'Тачпад'
#pacman -S xf86-input-synaptics --noconfirm
#wget 'https://like913.github.io/confug/10-synaptics.conf'

echo '>> '
pacman -S ntfs-3g exfat-utils --noconfirm
#echo 'Видеокарта'
#echo 'intel'
#pacman -S xf86-video-intel --noconfirm
#wget 'https://like913.github.io/confug/20-intel.conf'
#echo 'Настрока DRM'
#sed -i 's/MODULES=()/MODULES=(i915)/g' /etc/mkinitcpio.conf

#echo 'nvidia'
#pacman -S nvidia nvidia-utils lib32-nvidia-utils nvidia-settings --noconfirm
## После перезагрузки выполнить sudo nvidia-xconfig для настройки видеокары
## sudo nvidia-xconfig --prime необходимо для конфигурирования драйвера в совместимом режиме с картой intel

#echo 'AMD' #Установка и настройка AMD не тестировалось
#pacman -S xf86-video-amdgpu --noconfirm

echo '>> VirtualBox'
pacman -S virtualbox-guest-utils --noconfirm

echo '--------------------------------------------------'
echo '|           Установка Display Manager            |'
echo '--------------------------------------------------'
# раскомментировать блок SDDM или LXDM
echo '>> Установка sddm'
pacman -S sddm sddm-kcm --noconfirm
systemctl enable sddm

#echo '>> Настрока DRM nVidia'
#sed -i 's/MODULES=()/MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)/g' /etc/mkinitcpio.conf
# Настройка SDDM для nVidia PRIME
#echo 'xrandr --setprovideroutputsource modesetting NVIDIA-0' >> /usr/share/sddm/scripts/Xsetup
#echo 'xrandr --auto' >> /usr/share/sddm/scripts/Xsetup

#echo 'Установка lxdm'
#pacman -S lxdm --noconfirm
#systemctl enable lxdm

echo '>> Установка настройки сети'
pacman -S networkmanager --noconfirm
systemctl enable NetworkManager

echo '--------------------------------------------------'
echo '|         Установка Desktop Environment          |'
echo '--------------------------------------------------'
#echo '>> Cinnamon'
#pacman -S cinnamon cinnamon-translations --noconfirm
#pacman -S gnomme-terminal

#echo '>> Deepin'
#pacman -S deepin --noconfirm

echo '>> KDE Plasma'
pacman -S phonon-qt5-vlc
pacman -Sy plasma-meta kdebase packagekit-qt5
echo '>  Дополнительный софт для KDE'
pacman -S konsole partitionmanager spectacle okular --noconfirm
pacman -Rsnc konqueror kwrite ark --noconfirm

echo '>> Bluetooth pulseaudio и alsa поддержка звука'
pacman -Sy bluedevil pulseaudio-bluetooth alsa-utils pulseaudio-equalizer-ladspa --noconfirm
systemctl enable bluetooth.service

#echo 'XFCE'
#pacman -S xfce4 xfce4-goodies --noconfirm

echo '--------------------------------------------------'
echo '|        Установка дополнительного софта         |'
echo '--------------------------------------------------'
echo 'PS1="\e[0;31m\u\e[m@\e[1;90m\h\e[m \e[1;97m\W\e[m # "' >> /root/.bashrc
echo 'PS1="\e[0;34m\u\e[m@\e[1;90m\h\e[m \e[1;97m\W\e[m # "' >> /home/$username/.bashrc

echo '>> Настройка папок пользователя'
pacman -S xdg-user-dirs --noconfirm

pacman -Syu
pacman -S git --noconfirm

echo '>> Установка pacaur'
aur auracle-git
aur pacaur

echo '>> Установка микрокода ядра aic94xx и wd719x'
#sudo -u $username pacaur -S aic94xx-firmware wd719x-firmware
aur aic94xx-firmware
aur wd719x-firmware

mkinitcpio -p linux

echo '>> Установка octopi'
aur alpm_octopi_utils
aur octopi

echo '>> Установка Firewall'
pacman -S ufw gufw --noconfirm
systemctl enable ufw.service

echo '>> Установка wine'
pacman -S wine wine-mono wine_gecko winetricks --noconfirm
aur d9vk-bin
aur dxvk-bin
#winecfg
#setup_d9vk install
#setup_dxvk install
pacman -S vkd3d lib32-vkd3d --noconfirm

echo '>> Установка firefox'
pacman -S firefox firefox-i18n-ru --noconfirm
pacman -S thunderbird thunderbird-i18n-ru --noconfirm

echo '>> Установка VLC'
pacman -S vlc cheese --noconfirm

echo '>> Установка qbittorrent'
pacman -S qbittorrent --noconfirm

echo '>> Читалки, просмотр фото, музыки и прочее'
pacman -S neofetch baobab audacious --noconfirm
pacman -S gpicview --noconfirm

echo '>> Ставим шрифты'
pacman -S ttf-liberation ttf-dejavu --noconfirm
aur ttf-ms-fonts
aur ttf-tahoma

echo '>> Отчистка диска'
pacman -Scc --noconfirm
exit
