#!/bin/bash

rm -r ~/.wine32
rm -r ~/.wine
pacaur -S wine wine-mono wine_gecko winetricks vkd3d lib32-vkd3d d9vk-bin dxvk-bin
winecfg
setup_d9vk install
setup_dxvk install
WINEARCH=win32 WINEPREFIX=~/.wine32 winecfg
WINEARCH=win32 WINEPREFIX=~/.wine32 setup_d9vk install
WINEARCH=win32 WINEPREFIX=~/.wine32 setup_dxvk install
